using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Scanner : MonoBehaviour
{
    public float scanRange;
    public LayerMask targetLayer;
    public RaycastHit2D[] targets;

    public Transform nearestTarget;

    private void FixedUpdate()
    {
        targets = Physics2D.CircleCastAll(transform.position, scanRange, Vector2.zero, 0, targetLayer);
        nearestTarget = GetNearest();
    }

    private Transform GetNearest()
    {
        Transform result = null;
        float diff = 100;

        foreach(var target in targets)
        {
            float targetDiff = Vector3.Distance(transform.position, target.transform.position);

            if (targetDiff < diff)
            {
                diff = targetDiff;
                result = target.transform;
            }
        }

        return result;
    }
}
